export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCT_BY_CATEGORY = 'GET_PRODUCT_BY_CATEGORY';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';


export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';


export const ADMIN_GET_ALL_USERS = 'ADMIN_GET_ALL_USERS';
export const ADMIN_GET_USER_BY_ID = 'ADMIN_GET_USER_BY_ID';
export const ADMIN_EDIT_USER = 'ADMIN_EDIT_USER';
export const ADMIN_GET_ALL_PRODUCTS = 'ADMIN_GET_ALL_PRODUCTS';
export const ADMIN_GET_DELETED_PRODUCTS = 'ADMIN_GET_DELETED_PRODUCTS';
export const ADMIN_GET_PRODUCT_BY_ID = 'ADMIN_GET_PRODUCT_BY_ID';
export const ADMIN_EDIT_PRODUCT = 'ADMIN_EDIT_PRODUCT';
export const ADMIN_DELETE_PRODUCT = 'ADMIN_DELETE_PRODUCT';
export const ADMIN_RESTORE_PRODUCT = 'ADMIN_RESTORE_PRODUCT';
export const ADMIN_CREATE_PRODUCT = 'ADMIN_CREATE_PRODUCT';


export const PLACE_ORDER = 'PLACE_ORDER';
export const GET_ORDER_BY_CODE = 'GET_ORDER_BY_CODE';


export const USER_ERROR = 'USER_ERROR';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';


export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
